# .github/workflows/ci.yml
name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  # Job 1 - Test Addition
  test_add:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up CMake
        uses: lukka/get-cmake@v3
      
      - name: Build and Test Add
        run: |
          cmake .
          make
          ctest -R t1  # Run only test t1 (addition)

  # Job 2 - Test Subtraction
  test_sub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up CMake
        uses: lukka/get-cmake@v3
      
      - name: Build and Test Sub
        run: |
          cmake .
          make
          ctest -R t2  # Run only test t2 (subtraction)

  # Job 3 - Test Multiplication
  test_mul:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up CMake
        uses: lukka/get-cmake@v3
      
      - name: Build and Test Mul
        run: |
          cmake .
          make
          ctest -R t3  # Run only test t3 (multiplication)

  # Job 4 - Test Division
  test_div:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up CMake
        uses: lukka/get-cmake@v3
      
      - name: Build and Test Div
        run: |
          cmake .
          make
          ctest -R t4  # Run only test t4 (division)

  # Job 5 - Test Square
  test_square:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up CMake
        uses: lukka/get-cmake@v3
      
      - name: Build and Test Square
        run: |
          cmake .
          make
          ctest -R t5  # Run only test t5 (square)

  # Job 6 - Deploy
  deploy:
    runs-on: ubuntu-latest
    needs: [test_add, test_sub, test_mul, test_div, test_square]
    steps:
      - name: Echo Deployment
        run: echo "Déploiement de la solution"
